import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>meri.garden</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>meri.garden</main>
    </div>
  );
};

export default Home;
